import type { GraphiteTheme } from "@/components/charts/graphite/Chart";

/** Generated by Graphite. Import once; pass to every chart. */
export const graphiteTheme = {
  "defaultMode": "light",
  "surface": "solid",
  "modes": {
    "light": {
      "background": "#eef0f6",
      "surface": "#ffffff",
      "border": "rgba(16,20,40,.08)",
      "text": "#12141c",
      "muted": "#6b7085",
      "grid": "rgba(16,20,40,.07)",
      "track": "rgba(16,20,40,.05)"
    },
    "dark": {
      "background": "#0d0f15",
      "surface": "#151821",
      "border": "rgba(255,255,255,.06)",
      "text": "#f4f5f9",
      "muted": "#8a90a6",
      "grid": "rgba(255,255,255,.07)",
      "track": "rgba(255,255,255,.05)"
    }
  },
  "palette": [
    "#2f80ff",
    "#38d9f5",
    "#7ce0a0",
    "#a78bfa"
  ],
  "font": "Space Grotesk",
  "radius": 16,
  "stroke": 2.5,
  "fill": 0.2,
  "curve": "smooth",
  "grid": true,
  "legend": true,
  "labels": false
} as const satisfies GraphiteTheme;

export type SeriesColor = (typeof graphiteTheme.palette)[number];
